### ISSUE TITLE
line length calculation, wrapping; is broken

### ISSUE THREAD

**Issue by oppiliappan** [NerdyPepper/pista#1]
cancelling tab completions, or accessing history sometimes results in lines like this, (`|` is the cursor)
```
$ echo f|echo foo
```
because bash cannot calculate line width correctly when colored characters (`$` here) are used.  
http://mywiki.wooledge.org/BashFAQ/053

removing the coloring works as a fix, but that is not acceptable.

**Comment by leomwilson** [comment]
I get the same issue w/ ZSH, in case that matters

**Comment by oppiliappan** [comment]
oh i see, i thought ZLE handled colors better. thanks for the heads up! i am yet to find a fix.

**Comment by oppiliappan** [comment]
@JoshMcguigan's fork of the `colored` crate provides a fix for bash!
