### ISSUE TITLE
Quick feedback from a powerline shell user

### ISSUE THREAD

**Issue by JoshMcguigan** [NerdyPepper/pista#3]
Hey, thanks for sharing this. It looks great. I'm typically a powerline shell user, but I'm considering a switch. I wanted to leave some quick feedback with initial thoughts, but feel free to ignore/close if they don't align with the direction you wanted to go.

1. Does the readme describe (or show) what minimal mode changes? I couldn't figure it out.
2. Any thoughts on having a different visual git status when you have local commits that haven't been pushed yet?

**Comment by oppiliappan** [comment]
0. feel free to give suggestions/open issues!
1. i will address this in the next commit, but it simply displays the prompt on one line and strips away some extra spaces. you can edit `src/main.rs` to your liking, it is fairly straightforward!
2. `pista` displays a `↑` `↓` character if `HEAD` is ahead/behind of the last cached upstream. if you made some commits, but haven't pushed them, you should see an up arrow!

**Comment by JoshMcguigan** [comment]
Thanks for the quick response. I just installed pista, and found that the default light grey font doesn't show up well on a light themed terminal. It would be nice if there was a simple way to override that color, or possibly even better, if pista can detect my terminal background color and set it's font color automatically (not sure if this is possible?).

**Comment by oppiliappan** [comment]
all the colours are [configurable](https://github.com/nerdypepper/pista#configuration). just add 
```shell
export BRANCH_COLOR="green"
```
to your `.bashrc` or `.zshrc` and restart the shell (`exec bash/zsh`).this will change the colour of the arrow as well!

readability is subjective, so i prefer giving the user the option of changing colours.

**Comment by JoshMcguigan** [comment]
Thanks for that. For future readers, it was actually the `CWD_COLOR` that I was looking for. 

Last thing, I have noticed on two different machines (one ubuntu and one fedora, using default terminal in both) some strange behavior when I am entering a command and it breaks onto a new line.

The ubuntu machine overlaps the current line when the command should break to the next line. The fedora machine breaks to the next line, but if I then delete some characters from the beginning, the end of the command is padded with the last character of the command, and I am limited in how much I can delete. If you aren't able to reproduce I can try to explain more clearly.

**Comment by oppiliappan** [comment]
ah i am aware of this [issue](https://github.com/NerdyPepper/pista/issues/1). the fix (for bash users atleast) would bubble up to rewriting the `colored` crate! zsh users can run `pista` with the `-z` flag.

**Comment by JoshMcguigan** [comment]
Ah I missed that issue, sorry about that. What specifically would need to change in the colored crate? Quickly looking at that repo I didn't see any relevant open issues, but if there is a clear scope for the fix I wouldn't mind taking it on.

**Comment by oppiliappan** [comment]
the issue is extremely specific, it stems from GNU Readline's method of calculation of line length. non-printing escape sequences (eg.: `\x1b[31m` to produce red text) tend to confuse its calculation, producing warped results.

the fix is, to wrap every occurrence of such a sequence with a `\001` and a `\002`. the issue hasn't shown up anywhere because of how explicit it is!

**Comment by JoshMcguigan** [comment]
Thanks for the follow up. I started a fix for this in mackwic/colored#57, but there was a lot of test breakage (tests which compare colored to a "reference implementation"). I'm not sure I'll get around to completing the change, but I think it might work as is for your crate. 

In the mean time, I wonder if somehow disabling color just for the prompt would solve this problem for most pista users (users who use two lines, not the minimal version)?

**Comment by JoshMcguigan** [comment]
As a follow up, I swapped the colored dependency to point to my fork and re-installed pista and it seems to have resolved the issue for me.

**Comment by oppiliappan** [comment]
sweet! if you update your fork, ill add it as pista's dep! thank you for your time and effort!

i wonder if it would work alright in zsh.

**Comment by JoshMcguigan** [comment]
What are you looking to have updated? You can use this as is in pista by updating the `Cargo.toml` with `colored = { git = "https://github.com/JoshMcguigan/colored", branch = "char-count" }` in place of the existing dependency.

**Comment by oppiliappan** [comment]
ah my bad, i didnt notice the `char-count` branch. it works perfectly! this will also close #1 

thank you so much for your contribution!
