### ISSUE TITLE
Tilde abbreviation works in a weird way

### ISSUE THREAD

**Issue by shdown** [NerdyPepper/pista#5]
```
[~]-[%] echo $HOME $PWD
/home/v /home/v
$

[~]-[%] SHORTEN_CWD=0 HOME= .cargo/bin/pista
~/~h~o~m~e~/~v~  
$

[~]-[%] SHORTEN_CWD=0 HOME=/ .cargo/bin/pista
~home~v  
$

[~]-[%] SHORTEN_CWD=0 HOME=/h .cargo/bin/pista
~ome/v  
$

[~]-[%] mkdir -p home/v && cd home/v
[~/home/v]-[%] SHORTEN_CWD=0 /home/v/.cargo/bin/pista
~~
$
```

**Comment by oppiliappan** [comment]
ah edge cases! these have been fixed by  ff37975. please let me know if they persist.

**Comment by shdown** [comment]
Are you sure that, with `HOME=/` and `PWD=/home/v`, the output should be `~home/v`?

Are you sure that, with `HOME=/home/v` and `PWD=/home/vincent`, the output should be `~incent`?

**Comment by oppiliappan** [comment]
the output is indeed buggy with those settings, but those cases can simply not occur!

on unix systems the home directory is `/home/user` and `/root` for the superuser, never `/`. similar patterns on Mac/BSD as well. 

your second point is an issue. i dont really use multiple users, and it didn't cross my mind.

**Comment by shdown** [comment]
> but those cases can simply not occur!

To claim such a thing, you need to reference a standard. FHS [explicitly says the following](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s08.html):

> The setup will differ from host to host. Therefore, no program should assume any specific location for a home directory, rather it should query for it.

I have personally encountered `HOME=/` situation on a broken system.

On Linux, nothing prevents me from doing `useradd -d / myuser`, directly contradicting your claim.

**Comment by oppiliappan** [comment]
fair enough. basic string replacement is probably not the way to go. i will look into some other prompt implementations and see what's best.

**Comment by shdown** [comment]
I think it works like this: replace if the working directory either *equals* `${HOME}`, or starts with `${HOME}/`.

**Comment by oppiliappan** [comment]
the latest commit should fix this! first occurrence of `${HOME}` is replaced, if it follows the above condition. please take a look and let me know if its alright!

sorry for the delay! i was away for a quite a while haha
