### ISSUE TITLE
Clearing prompt with ^u is buggy

### ISSUE THREAD

**Issue by alassek** [NerdyPepper/pista#8]
OS: macOS 10.13.6
Shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

**Observed behavior:**
When command prompt has a number of characters equal or greater to 22, clearing the prompt with `^u` leaves the first 18 characters visible. They are not executed when enter is pressed.

**Expected Behavior:**
`^u` should clear the entire prompt

[![asciicast](https://asciinema.org/a/Kpi1hPIfTRpef9OLFTiZqrnEk.svg)](https://asciinema.org/a/Kpi1hPIfTRpef9OLFTiZqrnEk)

**Comment by evanrichter** [comment]
cannot reproduce on linux/zsh

**Comment by icyphox** [comment]
Can’t repro here either. Works as intended.

**Comment by oppiliappan** [comment]
seems to be related to #1. 

looping in @JoshMcguigan.

**Comment by JoshMcguigan** [comment]
@alassek Did you install pista by cloning the repo or via crates.io? I believe the version on crates.io still doesn't have the fix for #1, and this could potentially explain your issues.

**Comment by nlfiedler** [comment]
Probably it's a version thing. Using 0.1.1 on macOS with bash 5.0.7 reproduces the problem.

**Comment by JoshMcguigan** [comment]
@nlfiedler I believe version 0.1.1 should have the colored fix, which I thought may solve this problem. I'm wondering if it is somehow MacOS related as I don't see the issue on Linux. @icyphox what OS, terminal emulator, and shell are you using?

**Comment by icyphox** [comment]
@JoshMcguigan Debian 10, xfce4-terminal (although I don’t see how this helps) and zsh.

**Comment by nlfiedler** [comment]
Problem goes away for me with version 0.1.2 (built from source).

**Comment by oppiliappan** [comment]
yep! @JoshMcguigan's crate is working just fine. it looks like there were some hitches in linking it with pista because it hasn't been published to crates.io (cargo is a very choosy with dependencies).

@alassek give it a go and let me know!

**Comment by alassek** [comment]
@JoshMcguigan I followed the instructions in the README which (at the time) meant cargo. I’ll give it another try when I have a free moment.

**Comment by alassek** [comment]
Removing the cargo version and building 0.1.2 from source resolves the issue for me
