### ISSUE TITLE
Instructions on how to build from source, please

### ISSUE THREAD

**Issue by nlfiedler** [NerdyPepper/pista#9]
And thank you.

Looks like `colored` is a git submodule, but there is no `.gitmodules` file present, so I cannot build pista from source. Instructions would also be a good idea, in general, even if it is trivial. That way others can know if they are overlooking something simple.

**Comment by oppiliappan** [comment]
alright, i think its good to go now. i dont know why `.gitmodules` was not created when i did `git submodule add`.

to install rust and cargo,
```shell
$ curl https://sh.rustup.rs -sSf | sh
Rust is installed now. Great!

# check if you have the right version
$ rustc --version
rustc 1.36.0 (a53f9df32 2019-07-03)

# update if you dont have the right version
$ rustup update
```

to install `pista` from source,

```shell
$ git clone https://github.com/nerdypepper/pista --recurse-submodules
$ cargo install --path ./pista --force    # edited to @nlfiedler's suggestion

# check if pista is installed
$ ~/.cargo/bin/pista -V
Pista 0.1.2
```

it seems to be working fine on my linux vm, let me know if you need anything.
ill update the readme with full installation instructions.

**Comment by nlfiedler** [comment]
If you change `cargo install --path ./ --force` to `cargo install --path pista --force` then it will work, without having to add a `cd pista` in between. Thanks for creating this and staying on top of things.

**Comment by oppiliappan** [comment]
ah thats right, ill fix that. 

cheers!

**Comment by setop** [comment]
I was looking for a BUILD file.
It is not so easy.

First, I had to use `--recurse-submodules` which is not trivial.
Second, and it is not explain even in this issue, I had to install "libssl-dev".
